### ISSUE TITLE
ci: Add funding

### ISSUE THREAD

**Issue by pythoninthegrass** [LakshmanTurlapati/ProKeys#1]
Hi @LakshmanTurlapati.

Like what you've done here! While I ended up using Karabiner instead, thought I'd chime in that you should setup [GitHub sponsorship](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository).

I use the GitHub option like their example:
```yaml
# FUNDING.yml
github: [octocat, surftocat]
patreon: octocat
tidelift: npm/octo-package
custom: ["https://www.paypal.me/octocat", octocat.com]
```

Best of luck!
